export const PROJECTS = [
  {
    id: "p001",
    title: "NeuralVault",
    description: "A distributed AI model registry with real-time inference endpoints and version control for production ML pipelines.",
    tags: ["AI/ML", "Python", "FastAPI", "Docker"],
    category: "AI/ML",
    status: "Ongoing",
    likes: 142,
    rating: 4.9,
    github: "https://github.com",
    demo: null,
    members: [
      { name: "Arjun K", avatar: "AK" },
      { name: "Priya S", avatar: "PS" },
      { name: "Rahul M", avatar: "RM" },
    ],
    accentColor: "#C0001A",
    bgPattern: "neural",
    featured: true,
  },
  {
    id: "p002",
    title: "CodeCraft CLI",
    description: "Terminal-first project scaffolding tool. Generates production-ready monorepos in seconds with opinionated defaults.",
    tags: ["DevOps", "Node.js", "Rust"],
    category: "DEVOPS",
    status: "Completed",
    likes: 98,
    rating: 4.7,
    github: "https://github.com",
    demo: "https://demo.com",
    members: [
      { name: "Sneha R", avatar: "SR" },
      { name: "Kiran B", avatar: "KB" },
    ],
    accentColor: "#8B4500",
    bgPattern: "grid",
    featured: false,
  },
  {
    id: "p003",
    title: "Luminary UI",
    description: "Open-source design system built for dark-mode-first applications. 80+ components, fully accessible.",
    tags: ["Design", "React", "TypeScript"],
    category: "DESIGN",
    status: "Ongoing",
    likes: 211,
    rating: 4.8,
    github: "https://github.com",
    demo: "https://demo.com",
    members: [
      { name: "Aditi N", avatar: "AN" },
      { name: "Vikram C", avatar: "VC" },
      { name: "Tanvi D", avatar: "TD" },
      { name: "Rohan S", avatar: "RS" },
    ],
    accentColor: "#4A0080",
    bgPattern: "dots",
    featured: true,
  },
  {
    id: "p004",
    title: "FlowMapper",
    description: "Real-time network topology visualizer with live packet capture and anomaly detection for enterprise infrastructure.",
    tags: ["Web", "D3.js", "WebSocket", "Go"],
    category: "WEB",
    status: "Completed",
    likes: 76,
    rating: 4.5,
    github: "https://github.com",
    demo: null,
    members: [
      { name: "Dev P", avatar: "DP" },
    ],
    accentColor: "#005580",
    bgPattern: "lines",
    featured: false,
  },
  {
    id: "p005",
    title: "PocketMed",
    description: "Offline-first mobile health tracker with AI-powered symptom analysis and local-only data storage for privacy.",
    tags: ["Mobile", "React Native", "TFLite"],
    category: "MOBILE",
    status: "Ongoing",
    likes: 134,
    rating: 4.6,
    github: "https://github.com",
    demo: "https://demo.com",
    members: [
      { name: "Meera L", avatar: "ML" },
      { name: "Suresh V", avatar: "SV" },
    ],
    accentColor: "#006B3C",
    bgPattern: "neural",
    featured: false,
  },
  {
    id: "p006",
    title: "Obsidian Notes",
    description: "Git-native note-taking system with bidirectional linking, graph view, and end-to-end encrypted sync via your own server.",
    tags: ["Open Source", "Electron", "SQLite"],
    category: "OPEN SOURCE",
    status: "Ongoing",
    likes: 189,
    rating: 4.9,
    github: "https://github.com",
    demo: "https://demo.com",
    members: [
      { name: "Ananya B", avatar: "AB" },
      { name: "Nikhil T", avatar: "NT" },
      { name: "Zara K", avatar: "ZK" },
    ],
    accentColor: "#404040",
    bgPattern: "grid",
    featured: true,
  },
];
